export const translations = {
  // Autenticação
  auth: {
    welcomeBack: "Bem-vindo de volta",
    signIn: "Iniciar sessão na sua conta AssoGest",
    email: "Email",
    password: "Palavra-passe",
    signingIn: "Iniciando sessão...",
    signInButton: "Iniciar sessão",
    dontHaveAccount: "Não tem uma conta?",
    signUp: "Criar conta",
    loginFailed: "Falha ao iniciar sessão",

    createAccount: "Criar conta",
    getStarted: "Comece a usar o AssoGest hoje",
    fullName: "Nome completo",
    creatingAccount: "Criando conta...",
    createAccountButton: "Criar conta",
    alreadyHaveAccount: "Já tem uma conta?",
    registrationFailed: "Falha ao registar",

    loading: "Carregando...",
  },

  // Dashboard
  dashboard: {
    title: "Painel de controle",
    welcome: "Bem-vindo de volta! Aqui está uma visão geral das suas associações.",
    totalMembers: "Total de Membros",
    allRegistered: "Todos os membros registrados",
    activeMembers: "Membros Ativos",
    currentlyActive: "Atualmente ativos",
    totalRevenue: "Receita Total",
    thisMonth: "Este mês",
    pendingPayments: "Pagamentos Pendentes",
    awaitingPayment: "Aguardando pagamento",
    upcomingEvents: "Próximos Eventos",
    next30Days: "Próximos 30 dias",
    trending: "Tendência",
    fromLastMonth: "em relação ao mês passado",
    newEvents: "novos eventos",
    revenueOverview: "Visão Geral de Receita",
    monthlyRevenueTrends: "Tendências de receita e pagamentos mensais do ano passado",
    memberActivity: "Atividade de Membros",
    newMembers: "Novos Membros",
    inactiveMembers: "Membros Inativos",
    recentActivity: "Atividade Recente",
    upcomingEventsTitle: "Próximos Eventos",
  },

  // Navegação
  nav: {
    dashboard: "Painel de controle",
    associations: "Associações",
    members: "Membros",
    payments: "Pagamentos",
    events: "Eventos",
    reports: "Relatórios",
    settings: "Definições",
    logout: "Sair",
  },

  // Associações
  associations: {
    title: "Associações",
    createAssociation: "Criar Associação",
    found: "associação(ões) encontrada(s)",
    searchPlaceholder: "Pesquisar associações...",
    type: "Tipo",
    status: "Estado",
    noResults: "Tente ajustar seus filtros para encontrar o que você procura.",
    edit: "Editar",
    delete: "Eliminar",
    editTitle: "Editar Associação",
    createNew: "Criar Nova Associação",
    updateDetails: "Atualize os detalhes da associação abaixo.",
    fillDetails: "Preencha os detalhes para criar uma nova associação.",
    name: "Nome",
    description: "Descrição",
    foundedDate: "Data de Fundação",
    enterName: "Digite o nome da associação",
    enterDescription: "Digite a descrição da associação",
    selectType: "Selecionar tipo",
    selectStatus: "Selecionar estado",
    cooperative: "Cooperativa",
    association: "Associação",
    union: "União",
    active: "Ativo",
    inactive: "Inativo",
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Associação atualizada com sucesso",
    createdSuccess: "Associação criada com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente a associação",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Associação eliminada com sucesso",
  },

  // Membros
  members: {
    title: "Membros",
    addMember: "Adicionar Membro",
    found: "membro(s) encontrado(s)",
    searchPlaceholder: "Pesquisar membros...",
    getStarted: "Comece adicionando seu primeiro membro.",
    type: "Tipo",
    status: "Estado",
    editTitle: "Editar Membro",
    createNew: "Adicionar Novo Membro",
    updateDetails: "Atualize os detalhes do membro abaixo.",
    fillDetails: "Preencha os detalhes para adicionar um novo membro.",
    associationId: "ID da Associação",
    fullName: "Nome Completo",
    email: "Email",
    phone: "Telefone",
    joinDate: "Data de Adesão",
    membershipType: "Tipo de Associação",
    enterName: "Digite o nome do membro",
    enterEmail: "member@example.com",
    enterPhone: "+1 (555) 000-0000",
    regular: "Regular",
    honorary: "Honorário",
    associate: "Associado",
    active: "Ativo",
    inactive: "Inativo",
    suspended: "Suspenso",
    cancel: "Cancelar",
    add: "Adicionar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Membro atualizado com sucesso",
    addedSuccess: "Membro adicionado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o membro",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Membro eliminado com sucesso",
  },

  // Pagamentos
  payments: {
    title: "Pagamentos",
    recordNew: "Registar Novo Pagamento",
    found: "pagamento(s) encontrado(s)",
    searchPlaceholder: "Pesquisar pagamentos...",
    type: "Tipo",
    status: "Estado",
    noResults: "Tente ajustar seus filtros para encontrar o que você procura.",
    download: "Descarregar",
    edit: "Editar",
    delete: "Eliminar",
    editTitle: "Editar Pagamento",
    createNew: "Registar Novo Pagamento",
    updateDetails: "Atualize os detalhes do pagamento abaixo.",
    fillDetails: "Preencha os detalhes para registar um novo pagamento.",
    memberId: "ID do Membro",
    description: "Descrição",
    amount: "Valor",
    paymentDate: "Data do Pagamento",
    paymentType: "Tipo de Pagamento",
    enterMemberId: "Digite o ID do membro",
    enterDescription: "Digite a descrição do pagamento",
    enterAmount: "0.00",
    membership: "Associação",
    donation: "Doação",
    event: "Evento",
    other: "Outro",
    pending: "Pendente",
    completed: "Concluído",
    failed: "Falhou",
    refunded: "Reembolsado",
    cancel: "Cancelar",
    record: "Registar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Pagamento atualizado com sucesso",
    recordedSuccess: "Pagamento registado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o registo de pagamento de",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Pagamento eliminado com sucesso",
  },

  // Eventos
  events: {
    title: "Eventos",
    createEvent: "Criar Evento",
    found: "evento(s) encontrado(s)",
    searchPlaceholder: "Pesquisar eventos...",
    editTitle: "Editar Evento",
    createNew: "Criar Novo Evento",
    updateDetails: "Atualize os detalhes do evento abaixo.",
    fillDetails: "Preencha os detalhes para criar um novo evento.",
    associationId: "ID da Associação",
    title2: "Título",
    description: "Descrição",
    dateTime: "Data e Hora",
    location: "Local",
    capacity: "Capacidade",
    attendees: "Participantes",
    enterTitle: "Digite o título do evento",
    enterLocation: "Digite o local",
    enterCapacity: "50",
    enterAttendees: "0",
    upcoming: "Próximo",
    ongoing: "Em andamento",
    completed: "Concluído",
    cancelled: "Cancelado",
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Evento atualizado com sucesso",
    createdSuccess: "Evento criado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o evento",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Evento eliminado com sucesso",
  },

  // Relatórios
  reports: {
    title: "Relatórios",
    description: "Gere e consulte relatórios analíticos",
    generateReport: "Gerar Relatório",
    reportHistory: "Histórico de Relatórios",
    selectType: "Selecionar tipo de relatório",
    membershipReport: "Relatório de Associação",
    financialReport: "Relatório Financeiro",
    eventReport: "Relatório de Eventos",
    activityReport: "Relatório de Atividade",
    generate: "Gerar",
    download: "Descarregar",
  },

  // Definições
  settings: {
    title: "Definições",
    description: "Gerencie sua conta e preferências de aplicação",
    profileTab: "Perfil",
    notificationsTab: "Notificações",
    securityTab: "Segurança",
    appearanceTab: "Aparência",

    profileInformation: "Informações de Perfil",
    updatePersonal: "Atualize suas informações pessoais e detalhes de contato",
    name: "Nome Completo",
    email: "Endereço de Email",
    role: "Papel",
    enterName: "Digite seu nome",
    enterEmail: "Digite seu email",
    save: "Guardar Alterações",

    notificationPreferences: "Preferências de Notificação",
    chooseNotifications: "Escolha como deseja receber notificações",
    emailNotifications: "Notificações por Email",
    receiveEmail: "Receba notificações por email",
    pushNotifications: "Notificações Push",
    receivePush: "Receba notificações push em seu navegador",
    frequency: "Frequência de Notificação",
    realtime: "Tempo Real",
    dailyDigest: "Resumo Diário",
    weeklySummary: "Resumo Semanal",
    saveNotifications: "Guardar Preferências",

    securitySettings: "Configurações de Segurança",
    manageAccount: "Gerencie sua segurança de conta e autenticação",
    currentPassword: "Palavra-passe Atual",
    newPassword: "Nova Palavra-passe",
    confirmPassword: "Confirmar Nova Palavra-passe",
    twoFactor: "Autenticação de Dois Fatores",
    addSecurity: "Adicione uma camada extra de segurança à sua conta",
    updateSecurity: "Atualizar Segurança",

    appearanceSettings: "Configurações de Aparência",
    customizeApp: "Personalize a aparência do aplicativo",
    theme: "Tema",
    light: "Claro",
    dark: "Escuro",
    system: "Sistema",
    language: "Idioma",
    english: "Português",
    french: "Francês",
    spanish: "Espanhol",
    dateFormat: "Formato de Data",
    mdy: "MM/DD/AAAA",
    dmy: "DD/MM/AAAA",
    ymd: "AAAA-MM-DD",
    saveAppearance: "Guardar Aparência",
  },

  // Onboarding
  onboarding: {
    step1Title: "Criar Associação",
    step1Desc: "Configure sua primeira associação",
    step2Title: "Convidar Membros",
    step2Desc: "Adicione membros à sua associação",
    step3Title: "Configurar Pagamentos",
    step3Desc: "Configure o sistema de pagamentos",
    skip: "Pular",
    next: "Próximo",
    finish: "Concluir",
  },

  // Cabeçalho
  header: {
    search: "Pesquisar membros, pagamentos, eventos...",
  },
}
