export const translations = {
  // Autenticação
  auth: {
    welcomeBack: "Bem-vindo de volta",
    signIn: "Iniciar sessão na sua conta uRight",
    email: "Email",
    password: "Palavra-passe",
    signingIn: "Iniciando sessão...",
    signInButton: "Iniciar sessão",
    dontHaveAccount: "Não tem uma conta?",
    signUp: "Criar conta",
    loginFailed: "Falha ao iniciar sessão",

    createAccount: "Criar conta",
    getStarted: "Comece a usar o uRight hoje",
    fullName: "Nome completo",
    creatingAccount: "Criando conta...",
    createAccountButton: "Criar conta",
    alreadyHaveAccount: "Já tem uma conta?",
    registrationFailed: "Falha ao registar",
  },

  // Dashboard
  dashboard: {
    title: "Painel de Controle",
    welcome: "Bem-vindo de volta! Aqui está uma visão geral das suas atividades.",
    totalMembers: "Total de Membros",
    allRegistered: "Todos os membros registrados",
    activeMembers: "Membros Ativos",
    currentlyActive: "Atualmente ativos",
    totalRevenue: "Receita Total",
    thisMonth: "Este mês",
    pendingPayments: "Pagamentos Pendentes",
    awaitingPayment: "Aguardando pagamento",
    upcomingEvents: "Próximos Eventos",
    next30Days: "Próximos 30 dias",
    trending: "Tendência",
    fromLastMonth: "em relação ao mês passado",
    newEvents: "novos eventos",
    revenueOverview: "Visão Geral de Receita",
    monthlyRevenueTrends: "Tendências de receita e pagamentos mensais do ano passado",
    memberActivity: "Atividade de Membros",
    newMembers: "Novos Membros",
    inactiveMembers: "Membros Inativos",
    recentActivity: "Atividade Recente",
    upcomingEventsTitle: "Próximos Eventos",
    loading: "Carregando dashboard...",
    revenue: "Receita",
    members: "Membros",
  },

  // Navegação
  nav: {
    dashboard: "Painel de Controle",
    associations: "Associações",
    members: "Membros",
    payments: "Pagamentos",
    events: "Eventos",
    communications: "Comunicações",
    finance: "Financeiro",
    reports: "Relatórios",
    users: "Utilizadores",
    settings: "Definições",
    logout: "Sair",
  },

  // Associações
  associations: {
    title: "Associações",
    createAssociation: "Criar Associação",
    found: "associação(ões) encontrada(s)",
    searchPlaceholder: "Pesquisar associações...",
    type: "Tipo",
    status: "Estado",
    noResults: "Tente ajustar seus filtros para encontrar o que você procura.",
    edit: "Editar",
    delete: "Eliminar",
    editTitle: "Editar Associação",
    createNew: "Criar Nova Associação",
    updateDetails: "Atualize os detalhes da associação abaixo.",
    fillDetails: "Preencha os detalhes para criar uma nova associação.",
    name: "Nome",
    description: "Descrição",
    foundedDate: "Data de Fundação",
    enterName: "Digite o nome da associação",
    enterDescription: "Digite a descrição da associação",
    selectType: "Selecionar tipo",
    selectStatus: "Selecionar estado",
    cooperative: "Cooperativa",
    association: "Associação",
    union: "União",
    active: "Ativo",
    inactive: "Inativo",
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Associação atualizada com sucesso",
    createdSuccess: "Associação criada com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente a associação",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Associação eliminada com sucesso",
  },

  // Membros
  members: {
    title: "Membros",
    addMember: "Adicionar Membro",
    found: "membro(s) encontrado(s)",
    searchPlaceholder: "Pesquisar membros...",
    getStarted: "Comece adicionando seu primeiro membro.",
    type: "Tipo",
    status: "Estado",
    editTitle: "Editar Membro",
    createNew: "Adicionar Novo Membro",
    updateDetails: "Atualize os detalhes do membro abaixo.",
    fillDetails: "Preencha os detalhes para adicionar um novo membro.",
    associationId: "ID da Associação",
    fullName: "Nome Completo",
    email: "Email",
    phone: "Telefone",
    joinDate: "Data de Adesão",
    membershipType: "Tipo de Associação",
    enterName: "Digite o nome do membro",
    enterEmail: "user@example.com",
    enterPhone: "+1 (555) 000-0000",
    regular: "Regular",
    honorary: "Honorário",
    associate: "Associado",
    active: "Ativo",
    inactive: "Inativo",
    suspended: "Suspenso",
    cancel: "Cancelar",
    add: "Adicionar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Membro atualizado com sucesso",
    addedSuccess: "Membro adicionado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o membro",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Membro eliminado com sucesso",
  },

  // Pagamentos
  payments: {
    title: "Pagamentos",
    recordNew: "Registar Novo Pagamento",
    found: "pagamento(s) encontrado(s)",
    searchPlaceholder: "Pesquisar pagamentos...",
    type: "Tipo",
    status: "Estado",
    noResults: "Tente ajustar seus filtros para encontrar o que você procura.",
    download: "Descarregar",
    edit: "Editar",
    delete: "Eliminar",
    editTitle: "Editar Pagamento",
    createNew: "Registar Novo Pagamento",
    updateDetails: "Atualize os detalhes do pagamento abaixo.",
    fillDetails: "Preencha os detalhes para registar um novo pagamento.",
    memberId: "ID do Membro",
    description: "Descrição",
    amount: "Valor",
    paymentDate: "Data do Pagamento",
    paymentType: "Tipo de Pagamento",
    enterMemberId: "Digite o ID do membro",
    enterDescription: "Digite a descrição do pagamento",
    enterAmount: "0.00",
    membership: "Associação",
    donation: "Doação",
    event: "Evento",
    other: "Outro",
    pending: "Pendente",
    completed: "Concluído",
    failed: "Falhou",
    refunded: "Reembolsado",
    cancel: "Cancelar",
    record: "Registar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Pagamento atualizado com sucesso",
    recordedSuccess: "Pagamento registado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o registo de pagamento de",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Pagamento eliminado com sucesso",
  },

  // Eventos
  events: {
    title: "Eventos",
    createEvent: "Criar Evento",
    found: "evento(s) encontrado(s)",
    searchPlaceholder: "Pesquisar eventos...",
    editTitle: "Editar Evento",
    createNew: "Criar Novo Evento",
    updateDetails: "Atualize os detalhes do evento abaixo.",
    fillDetails: "Preencha os detalhes para criar um novo evento.",
    associationId: "ID da Associação",
    eventTitle: "Título",
    description: "Descrição",
    dateTime: "Data e Hora",
    location: "Local",
    capacity: "Capacidade",
    attendees: "Participantes",
    enterTitle: "Digite o título do evento",
    enterLocation: "Digite o local",
    enterCapacity: "50",
    enterAttendees: "0",
    upcoming: "Próximo",
    ongoing: "Em andamento",
    completed: "Concluído",
    cancelled: "Cancelado",
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Evento atualizado com sucesso",
    createdSuccess: "Evento criado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o evento",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Evento eliminado com sucesso",
    rsvp: "Confirmar Presença",
    attendance: "Marcar Presença",
    confirmed: "Confirmado",
    declined: "Recusado",
    pending: "Pendente",
    present: "Presente",
    absent: "Ausente",
    attendanceRate: "Taxa de Presença",
    rsvps: "Confirmações",
    noRSVPs: "Sem confirmações",
  },

  // Comunicações
  communications: {
    title: "Comunicações",
    subtitle: "Gerir alertas, mensagens e notificações",
    createAlert: "Criar Alerta",
    sendMessage: "Enviar Mensagem",
    alertType: "Tipo de Alerta",
    systemAlert: "Alerta do Sistema",
    manualMessage: "Mensagem Manual",
    automaticAlert: "Alerta Automático",
    recipients: "Destinatários",
    selectRecipients: "Selecionar destinatários",
    message: "Mensagem",
    enterMessage: "Digite a mensagem...",
    subject: "Assunto",
    enterSubject: "Digite o assunto...",
    sendTo: "Enviar para",
    sendToAll: "Enviar para todos",
    sendToAssociation: "Enviar para associação",
    sendToGroup: "Enviar para grupo",
    schedule: "Agendar",
    scheduleTime: "Horário de envio",
    immediate: "Imediatamente",
    readStatus: "Estado de leitura",
    read: "Lido",
    unread: "Não lido",
    sent: "Enviado",
    delivered: "Entregue",
    failed: "Falhou",
    sending: "Enviando...",
    cancel: "Cancelar",
    send: "Enviar",
    saving: "Guardando...",
    sentSuccess: "Mensagem enviada com sucesso",
    createdSuccess: "Alerta criado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente a mensagem",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Mensagem eliminada com sucesso",
    noMessages: "Sem mensagens",
    noAlerts: "Sem alertas",
  },

  // Financeiro
  finance: {
    title: "Financeiro",
    subtitle: "Resumo financeiro e relatórios",
    summary: "Resumo",
    byAssociation: "Por Associação",
    export: "Exportar",
    exportCSV: "Exportar CSV",
    exportJSON: "Exportar JSON",
    exportPDF: "Exportar PDF (futuro)",
    totalRevenue: "Receita Total",
    totalExpenses: "Despesas Totais",
    balance: "Saldo",
    delinquency: "Inadimplência",
    period: "Período",
    monthly: "Mensal",
    quarterly: "Trimestral",
    annually: "Anual",
    january: "Janeiro",
    february: "Fevereiro",
    march: "Março",
    april: "Abril",
    may: "Maio",
    june: "Junho",
    july: "Julho",
    august: "Agosto",
    september: "Setembro",
    october: "Outubro",
    november: "Novembro",
    december: "Dezembro",
    association: "Associação",
    member: "Membro",
    amount: "Valor",
    status: "Estado",
    daysOverdue: "Dias atrasados",
    paymentDue: "Pagamento devido",
    noData: "Sem dados",
    generating: "Gerando...",
    downloadSuccess: "Ficheiro baixado com sucesso",
    error: "Erro ao exportar",
  },

  // Utilizadores
  users: {
    title: "Utilizadores",
    subtitle: "Gerir utilizadores e roles",
    createUser: "Criar Utilizador",
    found: "utilizador(es) encontrado(s)",
    searchPlaceholder: "Pesquisar utilizadores...",
    name: "Nome",
    email: "Email",
    role: "Role",
    status: "Estado",
    createdAt: "Criado em",
    editTitle: "Editar Utilizador",
    createNew: "Criar Novo Utilizador",
    updateDetails: "Atualize os detalhes do utilizador abaixo.",
    fillDetails: "Preencha os detalhes para criar um novo utilizador.",
    enterName: "Digite o nome do utilizador",
    enterEmail: "user@example.com",
    selectRole: "Selecionar role",
    superadmin: "Superadmin",
    admin: "Admin",
    secretary: "Secretário",
    member: "Membro",
    active: "Ativo",
    inactive: "Inativo",
    pending: "Pendente",
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    saving: "Guardando...",
    updatedSuccess: "Utilizador atualizado com sucesso",
    createdSuccess: "Utilizador criado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o utilizador",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Utilizador eliminado com sucesso",
    noPermission: "Sem permissão para acessar esta página",
  },

  // Onboarding
  onboarding: {
    title: "Bem-vindo ao uRight",
    subtitle: "Vamos configurar a sua conta em 3 passos simples",
    step1: "Criar Associação",
    step2: "Convidar Membros",
    step3: "Configurar Pagamentos",
    step1Description: "Crie a sua primeira associação para começar",
    step2Description: "Adicione membros à sua associação",
    step3Description: "Configure as opções de pagamento",
    associationName: "Nome da Associação",
    associationType: "Tipo de Associação",
    associationDescription: "Descrição da Associação",
    memberEmail: "Email do Membro",
    addMember: "Adicionar Membro",
    skip: "Pular",
    next: "Próximo",
    finish: "Concluir",
    completing: "Completando...",
    completed: "Configuração completa! Bem-vindo ao uRight.",
    errorCreatingAssociation: "Erro ao criar associação",
    errorAddingMember: "Erro ao adicionar membro",
  },

  // Relatórios
  reports: {
    title: "Relatórios",
    generateReport: "Gerar Relatório",
    reportType: "Tipo de Relatório",
    selectPeriod: "Selecionar Período",
    downloadReport: "Descarregar Relatório",
    viewReport: "Visualizar Relatório",
    summary: "Resumo",
    details: "Detalhes",
    export: "Exportar",
    import: "Importar",
    saving: "Guardando...",
    savedSuccess: "Relatório guardado com sucesso",
    generating: "Gerando relatório...",
    generatedSuccess: "Relatório gerado com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente o relatório",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Relatório eliminado com sucesso",
  },

  // Definições
  settings: {
    title: "Definições",
    generalSettings: "Definições Gerais",
    languageSettings: "Definições de Idioma",
    saveSettings: "Guardar Definições",
    saving: "Guardando...",
    savedSuccess: "Definições guardadas com sucesso",
    deleteConfirm: "Tem a certeza?",
    deleteMessage: "Isto irá eliminar permanentemente as definições",
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletedSuccess: "Definições eliminadas com sucesso",
  },

  // Mensagens gerais
  common: {
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    warning: "Aviso",
    info: "Informação",
    confirm: "Confirmar",
    cancel: "Cancelar",
    close: "Fechar",
    back: "Voltar",
    next: "Próximo",
    previous: "Anterior",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Adicionar",
    create: "Criar",
    update: "Atualizar",
    remove: "Remover",
    view: "Ver",
    search: "Pesquisar",
    filter: "Filtrar",
    export: "Exportar",
    import: "Importar",
    download: "Descarregar",
    upload: "Carregar",
    noResults: "Sem resultados",
    noData: "Sem dados",
    tryAgain: "Tentar novamente",
    required: "Obrigatório",
    optional: "Opcional",
    or: "ou",
    and: "e",
    notFound: "Não encontrado",
    unauthorized: "Não autorizado",
    forbidden: "Proibido",
    serverError: "Erro do servidor",
  },
}
